### ISSUE TITLE
Create a settings view

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#21]
The settings view should be accessible via the tab bar (this might change later though). The tab system image is `gear`. There should be a new package in `AppPackages` called Settings. 

Figma design can be found [here](https://www.figma.com/design/XVOgIGB6rFFgJ6Jv7rXI4U/App?node-id=13-2939&t=w48F9DaWkXJ3X3hH-4)

> [!IMPORTANT] 
> All sections will be done in other tickets.

Here's what completes this ticket:
- [ ] There is a new Settings Package in the `AppPackages` folder for `Settings`
- [ ] The tab bar has a new tab for settings with the `gear` SF Symbol
- [ ] Tapping on the tab opens a view with the `Settings` title

**Comment by samuelsainz** [comment]
hey @heyjaywilson 👋 I'd love to contribute to PeakFit. Could I tackle this one? TIA!

**Comment by heyjaywilson** [comment]
@samuelsainz it's all yours!
