### ISSUE TITLE
Add a menu to the exercise list navigation bar

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#24]
A toolbar button needs to be added to the trailing side of the navigation bar that allows the user to open a menu. This menu will include sort options and a button to edit the list's name. This ticket does not implement those actions. It is to only add the menu to the toolbar

Tasks to complete this ticket

- [ ] Add a toolbar item to open a menu. Use `note.text` as the system symbol
- [ ] Add one item to the menu so that it opens

**Comment by Drag0ndust** [comment]
I would like to work on that issue

**Comment by heyjaywilson** [comment]
You got it @Drag0ndust!

**Comment by Drag0ndust** [comment]
@heyjaywilson  Just to be clear: The menu should be added to the `ExerciseListView`?

**Comment by heyjaywilson** [comment]
@Drag0ndust yup! That's correct because there will be sort items in there #25 #25 eventually
