### ISSUE TITLE
An exercise list's exercises should be sortable by the exercise's name

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#25]
Items to make this ticket complete

- [ ] Add an option in the list menu for "Alphabetical"
- [ ] Tapping on Alphabetical sorts the list based on the exercises' names

**Comment by Drag0ndust** [comment]
@heyjaywilson May I take this one also when my other PR is approved?

**Comment by heyjaywilson** [comment]
@Drag0ndust go for it!

**Comment by Drag0ndust** [comment]
@heyjaywilson PR is ready for review
