### ISSUE TITLE
Section titles in exercise detail view should not say "in # days" since they were done in the past

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#36]
The section titles in `ExerciseDetailView` should either say "# days ago" or the date the exercise reps were performed. They currently say "in # days" which implies they are in the future, and this is incorrect.

![image](https://github.com/user-attachments/assets/c43a41d7-f64b-4acf-9197-6d72dcb7de66)

---

Here is thie [figma](https://www.figma.com/design/XVOgIGB6rFFgJ6Jv7rXI4U/App?node-id=13-388&t=Didq3ouZomqiwF5h-4) doc showing what the `ExerciseDetailView()` is supposed to look like but with the default trailing padding.

**Comment by Brijeshthummar02** [comment]
i'll work on this.

**Comment by Drag0ndust** [comment]
I can have a look at this bug if it is available

**Comment by heyjaywilson** [comment]
@Drag0ndust since your PRs have gone through, do you want to try this one still?

**Comment by Drag0ndust** [comment]
I would leave it for someone else. If it is not taken by mid-October, I can have a look.

**Comment by SpacyRicochet** [comment]
Sounds like a nice one to start with. Can I take it then?

**Comment by heyjaywilson** [comment]
Sure can @SpacyRicochet!

**Comment by SpacyRicochet** [comment]
Okay, I thought that this would be an easy fix, but apparently iOS is very, very drunk. Look at the Saturday's a bit further in 😅 
<img width="220" alt="Screenshot 2024-10-05 at 20 23 02" src="https://github.com/user-attachments/assets/ad2707fe-b365-4b0c-b6fd-0d72a6aeae78">
