### ISSUE TITLE
Rep and weight input need the keyboard that only has numbers

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#37]
The weight and rep input labels need to have the keyboard that only has numbers. There's no reason to show the alphabet keys since the input can only be numerical.

These inputs are both in the `NewSetView`.

**Comment by Brijeshthummar02** [comment]
@heyjaywilson could you show me the path for this.

**Comment by heyjaywilson** [comment]
@Brijeshthummar02 I've updated the view these inputs are in. You already have an issue assigned to you. I'm only assigning issues to people who have no active issues. Once your other PR is accepted, I can assign you another issue.

**Comment by mike011** [comment]
I can do this. Pls review: https://github.com/heyjaywilson/peakfit/pull/57

**Comment by heyjaywilson** [comment]
@mike011 in the future, please wait for me to assign, but appreciate the work!
