### ISSUE TITLE
Fix NPM commands in the README.md

### ISSUE THREAD

**Issue by Drag0ndust** [heyjaywilson/peakfit#40]
There are some errors in the README.md for the NPM commands.

I can also do a quick fix for this.

**Comment by heyjaywilson** [comment]
I'll assign to you :) Thanks!

**Comment by Drag0ndust** [comment]
I can't commit to the repo because of a missing pre-commit hook. Can you please check it and add it?

This is the error message:
```
Couldn't find .git/COMMIT_EDITMSG
```

**Comment by Drag0ndust** [comment]
no, it doesn't add it for me

**Comment by heyjaywilson** [comment]
looking into it right now

**Comment by heyjaywilson** [comment]
Try running `npx husky .` in the terminal. I'm about to put up a PR but I still need to retest.
