### ISSUE TITLE
Add a menu to ExerciseListDetailView

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#45]
Add a menu to `ExerciseListDetailView`'s toolbar as the primary action. It needs to be able to open a menu for issues #23 and #25.

This ticket is complete when:
- [ ] A menu is added to the navigation toolbar with the SF Symbol `note.text`
- [ ] An item is in the menu to open it

**Comment by Drag0ndust** [comment]
May I take this?

**Comment by heyjaywilson** [comment]
You got it!
