### ISSUE TITLE
Exercise lists should be able to be sortable based on list name

### ISSUE THREAD

**Issue by heyjaywilson** [heyjaywilson/peakfit#46]
The lists on the "My Lists" view need to be able to be sorted alphabetically by the list names.

If you have a good SF Symbol to represent Alphabetical sorting, then please use it.

This ticket is complete when:
- [ ] There is an option in the list menu for "Alphabetical"
- [ ] Tapping on "Alphabetical" sorts the lists based on the list names

**Comment by mike011** [comment]
I got this :D

**Comment by mike011** [comment]
PR is up: https://github.com/heyjaywilson/peakfit/pull/63

**Comment by mike011** [comment]
pls close issue
